version: "3"
services:
  n8n:
    image: n8nio/n8n:1.94.1
    container_name: n8n
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=3f434c45ee0a.ngrok-free.app
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://3f434c45ee0a.ngrok-free.app
      - N8N_EDITOR_BASE_URL=https://3f434c45ee0a.ngrok-free.app
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=sth
      - N8N_BASIC_AUTH_PASSWORD=pwd
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - C:/n8n/n8n-data:/home/node/.n8n
    restart: unless-stopped
    stop_grace_period: 60s